services:
  mysql:
    image: mysql:8.0
    container_name: gestion_stages_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_stages
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/gestion_stages.sql:/docker-entrypoint-initdb.d/gestion_stages.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: gestion_stages_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: gestion_stages
      JWT_SECRET: stageflow_docker_secret_key
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: gestion_stages_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mysql_data: